spring:
  banner:
      location: classpath:/runbanner/banner.txt
server:
    port: 8081
    servlet:
        context-path: /ecosoft/api/v1/microservices
app:
  name: Microservices de clientes
  year: 2021
  ##Community, Pro
  edition: Community
  countries: es, ar, it, ca. br
